### PR TITLE
Fixed issue with playlists not showing all songs with Mobileclient

### PR DESCRIPTION
**Pull request by tlm2021**
I got so excited when I found this plugin that when it didn't work for me today I spent my whole day trying to fix it.

It looks like, when updating playlists while using the Mobileclient, it wasn't storing any of the songs it found in the 'all_music' table. Additionally, it was storing the trackId in the 'playlists_songs' table, instead of the normal 'id', causing issues with joining records. Finally, the table in 'all_music' didn't have a column that covered 'trackId'.

When trying to populate the list of tracks, it does a JOIN between 'playlists_songs' and 'songs', but first these records weren't making it into the table, and then when the table didn't have a column for that key. It would only work if you first updated "all_tracks", and even then "all_tracks" is only items added to your library, so any All Access songs you added to a playlist but not your library wouldn't show up.

So now instead I add the normal 'id' to the 'playlists_songs' table, and just store the trackId in the 'songs' table.

When trying to play a song using the Mobileclient, it didn't seem to like the normal 'id' that was being passed in, and came came back with "Not Found" errors. So now whatever's in the 'trackId' column is what gets fed into "__getSongStreamUrl". The 'trackId' column contains a 'trackId' attribute whenever it's found. When not, it falls back on the plain 'id'.

Works for me smoothly so far...but admittedly I haven't been testing long. And I think it's backwards compatible for people not using the Mobileclient, but I haven't been able to test that myself.

### CODE REVIEW

**Comment by vially** [comment]
Awesome. Thanks for your work! Merged.

**Comment by foreverguest** [comment]
These modifications break playlists for me, could you check if this version works for you: https://github.com/foreverguest/googlemusic-xbmc/tree/develop

**Comment by tlm2021** [comment]
Yeah, switching back to trackId breaks All Access tracks. But I've got a playlist now with a single uploaded, unmatched track and I can see the mismatch in song_id that's getting reported. 

I'll see if I can crack the mystery of how to uniquely identify tracks across both types.

**Comment by tlm2021** [comment]
Can you try this version:

https://github.com/tlm2021/googlemusic-xbmc/tree/develop

It looks like the combo to go with is storing the 'trackId' in the playlists_songs table, and updating songs() to use either "storeId" (if it exists), and fallback on plain (id) otherwise. I think 'trackId' will match storeId for all matched and  All Access tracks, and "id" in all other cases.

There is one other bug I'm trying to find. I've got one song that won't give me a stream url from the 'storeId', but it will from the 'id'. I think it has to do with them having swapped out a matched track on the backend, but I'm still looking. So far it's just the one track. I've got a couples routes in mind to fix that, but neither are super pretty.

**Comment by foreverguest** [comment]
Now playlists work, but a bunch of tracks fail to play with '404 Client Error: Not Found'. When the song id starts with 'T' it always fails for me. Probably matched tracks as you said.

**Comment by foreverguest** [comment]
Maybe if we store both fields 'id' and 'trackId' in playlist, like this: https://github.com/foreverguest/googlemusic-xbmc/commit/0b041526cc3a2d5f866d7f2e30bcff30d825001f#diff-865bb1ff44b83700610b4867d36b5cb3

**Comment by tlm2021** [comment]
Actually, I think maybe I was just favoring the wrong id.

https://github.com/tlm2021/googlemusic-xbmc/commit/f120e3967569f6dd65859068ba3cc0c919e72055

'trackId' is just a FK for one of two columns in a 'track', ("id" for all uploaded tracks -- matched or unmatched-- and "storeId" for All Access tracks). And 'id' doesn't exist for songs that have to use 'storeId'.

So I think just swapping the key I was favoring should do the trick. It works for me, including to my previously troublesome track.

It should work for you, since the behavior for non All-Access users should be identical to your version, just without the extra column in the table. Let me know if that isn't the case!

**Comment by foreverguest** [comment]
Yes, it works. Thanks.

**Pull request merged**
